//------------------------------------------------------------------------------
// <auto-generated>
//     Manual port from VB MySettings for WinNUT.Client (C#).
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System.Configuration;
using System.Runtime.CompilerServices;
using WinNUT_Client_Common;

namespace WinNUT_Client.Properties;

[CompilerGenerated]
internal sealed partial class Settings : ApplicationSettingsBase
{
    private static Settings? _defaultInstance;

    public static Settings Default => _defaultInstance ??= (Settings)Synchronized(new Settings());

    [UserScopedSetting, DefaultSettingValue("False")]
    public bool StartWithWindows
    {
        get => (bool)this[nameof(StartWithWindows)];
        set => this[nameof(StartWithWindows)] = value;
    }

    [UserScopedSetting, DefaultSettingValue("False")]
    public bool CloseToTray
    {
        get => (bool)this[nameof(CloseToTray)];
        set => this[nameof(CloseToTray)] = value;
    }

    [UserScopedSetting, DefaultSettingValue("False")]
    public bool MinimizeOnStart
    {
        get => (bool)this[nameof(MinimizeOnStart)];
        set => this[nameof(MinimizeOnStart)] = value;
    }

    [UserScopedSetting, DefaultSettingValue("False")]
    public bool MinimizeToTray
    {
        get => (bool)this[nameof(MinimizeToTray)];
        set => this[nameof(MinimizeToTray)] = value;
    }

    [UserScopedSetting, DefaultSettingValue("False")]
    public bool LG_LogToFile
    {
        get => (bool)this[nameof(LG_LogToFile)];
        set => this[nameof(LG_LogToFile)] = value;
    }

    [UserScopedSetting, DefaultSettingValue("0")]
    public int LG_LogLevel
    {
        get => (int)this[nameof(LG_LogLevel)];
        set => this[nameof(LG_LogLevel)] = value;
    }

    [UserScopedSetting, DefaultSettingValue("False")]
    public bool UP_CheckAtStart
    {
        get => (bool)this[nameof(UP_CheckAtStart)];
        set => this[nameof(UP_CheckAtStart)] = value;
    }

    [UserScopedSetting, DefaultSettingValue("0")]
    public int UP_AutoChkDelay
    {
        get => (int)this[nameof(UP_AutoChkDelay)];
        set => this[nameof(UP_AutoChkDelay)] = value;
    }

    [UserScopedSetting, DefaultSettingValue("0")]
    public int UP_Branch
    {
        get => (int)this[nameof(UP_Branch)];
        set => this[nameof(UP_Branch)] = value;
    }

    [UserScopedSetting]
    public DateTime UP_LastCheck
    {
        get => (DateTime)this[nameof(UP_LastCheck)];
        set => this[nameof(UP_LastCheck)] = value;
    }

    [UserScopedSetting, DefaultSettingValue("30")]
    public int PW_BattChrgFloor
    {
        get => (int)this[nameof(PW_BattChrgFloor)];
        set => this[nameof(PW_BattChrgFloor)] = value;
    }

    [UserScopedSetting, DefaultSettingValue("120")]
    public int PW_RuntimeFloor
    {
        get => (int)this[nameof(PW_RuntimeFloor)];
        set => this[nameof(PW_RuntimeFloor)] = value;
    }

    [UserScopedSetting, DefaultSettingValue("False")]
    public bool PW_Immediate
    {
        get => (bool)this[nameof(PW_Immediate)];
        set => this[nameof(PW_Immediate)] = value;
    }

    [UserScopedSetting, DefaultSettingValue("False")]
    public bool PW_RespectFSD
    {
        get => (bool)this[nameof(PW_RespectFSD)];
        set => this[nameof(PW_RespectFSD)] = value;
    }

    [UserScopedSetting, DefaultSettingValue("0")]
    public int PW_StopType
    {
        get => (int)this[nameof(PW_StopType)];
        set => this[nameof(PW_StopType)] = value;
    }

    [UserScopedSetting, DefaultSettingValue("15")]
    public int PW_StopDelaySec
    {
        get => (int)this[nameof(PW_StopDelaySec)];
        set => this[nameof(PW_StopDelaySec)] = value;
    }

    [UserScopedSetting, DefaultSettingValue("False")]
    public bool PW_UserExtendStopTimer
    {
        get => (bool)this[nameof(PW_UserExtendStopTimer)];
        set => this[nameof(PW_UserExtendStopTimer)] = value;
    }

    [UserScopedSetting, DefaultSettingValue("15")]
    public int PW_ExtendDelaySec
    {
        get => (int)this[nameof(PW_ExtendDelaySec)];
        set => this[nameof(PW_ExtendDelaySec)] = value;
    }

    [UserScopedSetting, DefaultSettingValue("nutserver host")]
    public string NUT_ServerAddress
    {
        get => (string)this[nameof(NUT_ServerAddress)];
        set => this[nameof(NUT_ServerAddress)] = value;
    }

    [UserScopedSetting, DefaultSettingValue("3493")]
    public int NUT_ServerPort
    {
        get => (int)this[nameof(NUT_ServerPort)];
        set => this[nameof(NUT_ServerPort)] = value;
    }

    [UserScopedSetting, DefaultSettingValue("UPS name")]
    public string NUT_UPSName
    {
        get => (string)this[nameof(NUT_UPSName)];
        set => this[nameof(NUT_UPSName)] = value;
    }

    [UserScopedSetting, DefaultSettingValue("1000")]
    public int NUT_PollIntervalMsec
    {
        get => (int)this[nameof(NUT_PollIntervalMsec)];
        set => this[nameof(NUT_PollIntervalMsec)] = value;
    }

    [UserScopedSetting]
    public SerializedProtectedString NUT_Username
    {
        get => this[nameof(NUT_Username)] as SerializedProtectedString ?? new SerializedProtectedString();
        set => this[nameof(NUT_Username)] = value;
    }

    [UserScopedSetting]
    public SerializedProtectedString NUT_Password
    {
        get => this[nameof(NUT_Password)] as SerializedProtectedString ?? new SerializedProtectedString();
        set => this[nameof(NUT_Password)] = value;
    }

    [UserScopedSetting, DefaultSettingValue("False")]
    public bool NUT_AutoReconnect
    {
        get => (bool)this[nameof(NUT_AutoReconnect)];
        set => this[nameof(NUT_AutoReconnect)] = value;
    }

    [UserScopedSetting, DefaultSettingValue("210")]
    public int CAL_VoltInMin
    {
        get => (int)this[nameof(CAL_VoltInMin)];
        set => this[nameof(CAL_VoltInMin)] = value;
    }

    [UserScopedSetting, DefaultSettingValue("270")]
    public int CAL_VoltInMax
    {
        get => (int)this[nameof(CAL_VoltInMax)];
        set => this[nameof(CAL_VoltInMax)] = value;
    }

    [UserScopedSetting, DefaultSettingValue("50")]
    public int CAL_FreqInNom
    {
        get => (int)this[nameof(CAL_FreqInNom)];
        set => this[nameof(CAL_FreqInNom)] = value;
    }

    [UserScopedSetting, DefaultSettingValue("40")]
    public int CAL_FreqInMin
    {
        get => (int)this[nameof(CAL_FreqInMin)];
        set => this[nameof(CAL_FreqInMin)] = value;
    }

    [UserScopedSetting, DefaultSettingValue("60")]
    public int CAL_FreqInMax
    {
        get => (int)this[nameof(CAL_FreqInMax)];
        set => this[nameof(CAL_FreqInMax)] = value;
    }

    [UserScopedSetting, DefaultSettingValue("210")]
    public int CAL_VoltOutMin
    {
        get => (int)this[nameof(CAL_VoltOutMin)];
        set => this[nameof(CAL_VoltOutMin)] = value;
    }

    [UserScopedSetting, DefaultSettingValue("270")]
    public int CAL_VoltOutMax
    {
        get => (int)this[nameof(CAL_VoltOutMax)];
        set => this[nameof(CAL_VoltOutMax)] = value;
    }

    [UserScopedSetting, DefaultSettingValue("0")]
    public int CAL_LoadMin
    {
        get => (int)this[nameof(CAL_LoadMin)];
        set => this[nameof(CAL_LoadMin)] = value;
    }

    [UserScopedSetting, DefaultSettingValue("100")]
    public int CAL_LoadMax
    {
        get => (int)this[nameof(CAL_LoadMax)];
        set => this[nameof(CAL_LoadMax)] = value;
    }

    [UserScopedSetting, DefaultSettingValue("6")]
    public int CAL_BattVMin
    {
        get => (int)this[nameof(CAL_BattVMin)];
        set => this[nameof(CAL_BattVMin)] = value;
    }

    [UserScopedSetting, DefaultSettingValue("18")]
    public int CAL_BattVMax
    {
        get => (int)this[nameof(CAL_BattVMax)];
        set => this[nameof(CAL_BattVMax)] = value;
    }

    [UserScopedSetting, DefaultSettingValue("True")]
    public bool IsFirstRun
    {
        get => (bool)this[nameof(IsFirstRun)];
        set => this[nameof(IsFirstRun)] = value;
    }
}
